// GENERATED FILE — do not hand-edit.
//
// Source: Local Government Directory (lgdirectory.gov.in), District LGD Codes
// export, via the India Data Portal OGDL mirror:
//   https://ckandev.indiadataportal.com/dataset/lgd-codes/resource/19df978a-675e-4ff5-8015-d0e1de447319
// Retrieved: 2026-07-17. Source data last updated 2023-10-20.
//
// `lgd_code` values are transcribed verbatim from that export — never invent a
// code; leave it null instead. `iso_code` is ISO 3166-2:IN, which the export
// does not carry, so it comes from a hand-maintained 36-row map keyed by LGD
// state code. Those reflect the 2023-11-23 ISO revision (IN-OR→IN-OD,
// IN-UT→IN-UK, IN-CT→IN-CG, IN-TG→IN-TS); older Indian systems may still emit
// the superseded forms.
//
// The one name normalisation applied: LGD renders the merged UT as "The Dadra
// and Nagar Haveli and Daman and Diu"; the leading article is stripped so it
// sorts under D and matches the ISO name.
//
// Consumed only by 1792700000000-CreateAddressAttributes.ts. It is a .ts module
// rather than .json deliberately: tsconfig.json sets no `resolveJsonModule`, and
// nest build type-checks src/migrations/**, so a JSON import would pass
// migration:run (ts-node runs transpileOnly) and then fail the build with TS2732.

export interface GeoSeedDistrict {
  name: string;
  lgd_code: string;
}

export interface GeoSeedState {
  name: string;
  lgd_code: string;
  iso_code: string;
  districts: GeoSeedDistrict[];
}

export interface GeoSeedCountry {
  name: string;
  iso2: string;
  iso3: string;
  dial_code: string;
}

export interface GeoSeed {
  country: GeoSeedCountry;
  states: GeoSeedState[];
}

export const INDIA_GEO: GeoSeed = {
  country: { name: 'India', iso2: 'IN', iso3: 'IND', dial_code: '+91' },
  states: [
    {
      name: 'Andaman and Nicobar Islands',
      lgd_code: '35',
      iso_code: 'IN-AN',
      districts: [
        { name: 'Nicobars', lgd_code: '603' },
        { name: 'North and Middle Andaman', lgd_code: '632' },
        { name: 'South Andamans', lgd_code: '602' },
      ],
    },
    {
      name: 'Andhra Pradesh',
      lgd_code: '28',
      iso_code: 'IN-AP',
      districts: [
        { name: 'Alluri Sitharama Raju', lgd_code: '745' },
        { name: 'Anakapalli', lgd_code: '744' },
        { name: 'Anantapur', lgd_code: '502' },
        { name: 'Annamayya', lgd_code: '753' },
        { name: 'Bapatla', lgd_code: '750' },
        { name: 'Chittoor', lgd_code: '503' },
        { name: 'East Godavari', lgd_code: '505' },
        { name: 'Eluru', lgd_code: '748' },
        { name: 'Guntur', lgd_code: '506' },
        { name: 'Kakinada', lgd_code: '746' },
        { name: 'Konaseema', lgd_code: '747' },
        { name: 'Krishna', lgd_code: '510' },
        { name: 'Kurnool', lgd_code: '511' },
        { name: 'Nandyal', lgd_code: '755' },
        { name: 'Ntr', lgd_code: '749' },
        { name: 'Palnadu', lgd_code: '751' },
        { name: 'Parvathipuram Manyam', lgd_code: '743' },
        { name: 'Prakasam', lgd_code: '517' },
        { name: 'Spsr Nellore', lgd_code: '515' },
        { name: 'Sri Sathya Sai', lgd_code: '754' },
        { name: 'Srikakulam', lgd_code: '519' },
        { name: 'Tirupati', lgd_code: '752' },
        { name: 'Visakhapatanam', lgd_code: '520' },
        { name: 'Vizianagaram', lgd_code: '521' },
        { name: 'West Godavari', lgd_code: '523' },
        { name: 'Y.s.r.', lgd_code: '504' },
      ],
    },
    {
      name: 'Arunachal Pradesh',
      lgd_code: '12',
      iso_code: 'IN-AR',
      districts: [
        { name: 'Anjaw', lgd_code: '628' },
        { name: 'Changlang', lgd_code: '229' },
        { name: 'Dibang Valley', lgd_code: '230' },
        { name: 'East Kameng', lgd_code: '231' },
        { name: 'East Siang', lgd_code: '232' },
        { name: 'Kamle', lgd_code: '718' },
        { name: 'Kra Daadi', lgd_code: '677' },
        { name: 'Kurung Kumey', lgd_code: '233' },
        { name: 'Leparada', lgd_code: '724' },
        { name: 'Lohit', lgd_code: '234' },
        { name: 'Longding', lgd_code: '666' },
        { name: 'Lower Dibang Valley', lgd_code: '235' },
        { name: 'Lower Siang', lgd_code: '719' },
        { name: 'Lower Subansiri', lgd_code: '236' },
        { name: 'Namsai', lgd_code: '678' },
        { name: 'Pakke Kessang', lgd_code: '723' },
        { name: 'Papum Pare', lgd_code: '237' },
        { name: 'Shi Yomi', lgd_code: '725' },
        { name: 'Siang', lgd_code: '679' },
        { name: 'Tawang', lgd_code: '238' },
        { name: 'Tirap', lgd_code: '239' },
        { name: 'Upper Siang', lgd_code: '240' },
        { name: 'Upper Subansiri', lgd_code: '241' },
        { name: 'West Kameng', lgd_code: '242' },
        { name: 'West Siang', lgd_code: '243' },
      ],
    },
    {
      name: 'Assam',
      lgd_code: '18',
      iso_code: 'IN-AS',
      districts: [
        { name: 'Bajali', lgd_code: '739' },
        { name: 'Baksa', lgd_code: '616' },
        { name: 'Barpeta', lgd_code: '280' },
        { name: 'Biswanath', lgd_code: '705' },
        { name: 'Bongaigaon', lgd_code: '281' },
        { name: 'Cachar', lgd_code: '282' },
        { name: 'Charaideo', lgd_code: '708' },
        { name: 'Chirang', lgd_code: '612' },
        { name: 'Darrang', lgd_code: '283' },
        { name: 'Dhemaji', lgd_code: '284' },
        { name: 'Dhubri', lgd_code: '285' },
        { name: 'Dibrugarh', lgd_code: '286' },
        { name: 'Dima Hasao', lgd_code: '299' },
        { name: 'Goalpara', lgd_code: '287' },
        { name: 'Golaghat', lgd_code: '288' },
        { name: 'Hailakandi', lgd_code: '289' },
        { name: 'Hojai', lgd_code: '709' },
        { name: 'Jorhat', lgd_code: '290' },
        { name: 'Kamrup', lgd_code: '291' },
        { name: 'Kamrup Metro', lgd_code: '618' },
        { name: 'Karbi Anglong', lgd_code: '292' },
        { name: 'Karimganj', lgd_code: '293' },
        { name: 'Kokrajhar', lgd_code: '294' },
        { name: 'Lakhimpur', lgd_code: '295' },
        { name: 'Majuli', lgd_code: '706' },
        { name: 'Marigaon', lgd_code: '296' },
        { name: 'Nagaon', lgd_code: '297' },
        { name: 'Nalbari', lgd_code: '298' },
        { name: 'Sivasagar', lgd_code: '300' },
        { name: 'Sonitpur', lgd_code: '301' },
        { name: 'South Salmara Mancachar', lgd_code: '707' },
        { name: 'Tamulpur', lgd_code: '756' },
        { name: 'Tinsukia', lgd_code: '302' },
        { name: 'Udalguri', lgd_code: '617' },
        { name: 'West Karbi Anglong', lgd_code: '710' },
      ],
    },
    {
      name: 'Bihar',
      lgd_code: '10',
      iso_code: 'IN-BR',
      districts: [
        { name: 'Araria', lgd_code: '188' },
        { name: 'Arwal', lgd_code: '611' },
        { name: 'Aurangabad', lgd_code: '189' },
        { name: 'Banka', lgd_code: '190' },
        { name: 'Begusarai', lgd_code: '191' },
        { name: 'Bhagalpur', lgd_code: '192' },
        { name: 'Bhojpur', lgd_code: '193' },
        { name: 'Buxar', lgd_code: '194' },
        { name: 'Darbhanga', lgd_code: '195' },
        { name: 'Gaya', lgd_code: '196' },
        { name: 'Gopalganj', lgd_code: '197' },
        { name: 'Jamui', lgd_code: '198' },
        { name: 'Jehanabad', lgd_code: '199' },
        { name: 'Kaimur (bhabua)', lgd_code: '200' },
        { name: 'Katihar', lgd_code: '201' },
        { name: 'Khagaria', lgd_code: '202' },
        { name: 'Kishanganj', lgd_code: '203' },
        { name: 'Lakhisarai', lgd_code: '204' },
        { name: 'Madhepura', lgd_code: '205' },
        { name: 'Madhubani', lgd_code: '206' },
        { name: 'Munger', lgd_code: '207' },
        { name: 'Muzaffarpur', lgd_code: '208' },
        { name: 'Nalanda', lgd_code: '209' },
        { name: 'Nawada', lgd_code: '210' },
        { name: 'Pashchim Champaran', lgd_code: '211' },
        { name: 'Patna', lgd_code: '212' },
        { name: 'Purbi Champaran', lgd_code: '213' },
        { name: 'Purnia', lgd_code: '214' },
        { name: 'Rohtas', lgd_code: '215' },
        { name: 'Saharsa', lgd_code: '216' },
        { name: 'Samastipur', lgd_code: '217' },
        { name: 'Saran', lgd_code: '218' },
        { name: 'Sheikhpura', lgd_code: '219' },
        { name: 'Sheohar', lgd_code: '220' },
        { name: 'Sitamarhi', lgd_code: '221' },
        { name: 'Siwan', lgd_code: '222' },
        { name: 'Supaul', lgd_code: '223' },
        { name: 'Vaishali', lgd_code: '224' },
      ],
    },
    {
      name: 'Chandigarh',
      lgd_code: '4',
      iso_code: 'IN-CH',
      districts: [{ name: 'Chandigarh', lgd_code: '44' }],
    },
    {
      name: 'Chhattisgarh',
      lgd_code: '22',
      iso_code: 'IN-CG',
      districts: [
        { name: 'Balod', lgd_code: '646' },
        { name: 'Baloda Bazar', lgd_code: '644' },
        { name: 'Balrampur', lgd_code: '649' },
        { name: 'Bastar', lgd_code: '374' },
        { name: 'Bemetara', lgd_code: '650' },
        { name: 'Bijapur', lgd_code: '636' },
        { name: 'Bilaspur', lgd_code: '375' },
        { name: 'Dantewada', lgd_code: '376' },
        { name: 'Dhamtari', lgd_code: '377' },
        { name: 'Durg', lgd_code: '378' },
        { name: 'Gariyaband', lgd_code: '645' },
        { name: 'Gaurella Pendra Marwahi', lgd_code: '734' },
        { name: 'Janjgir-champa', lgd_code: '379' },
        { name: 'Jashpur', lgd_code: '380' },
        { name: 'Kabirdham', lgd_code: '382' },
        { name: 'Kanker', lgd_code: '381' },
        { name: 'Khairgarh Chhuikhadan Gandai', lgd_code: '759' },
        { name: 'Kondagaon', lgd_code: '643' },
        { name: 'Korba', lgd_code: '383' },
        { name: 'Korea', lgd_code: '384' },
        { name: 'Mahasamund', lgd_code: '385' },
        { name: 'Manendragarh Chirimiri Bharatpur', lgd_code: '760' },
        { name: 'Mohla Manpur Ambagarh Chouki', lgd_code: '761' },
        { name: 'Mungeli', lgd_code: '647' },
        { name: 'Narayanpur', lgd_code: '637' },
        { name: 'Raigarh', lgd_code: '386' },
        { name: 'Raipur', lgd_code: '387' },
        { name: 'Rajnandgaon', lgd_code: '388' },
        { name: 'Sakti', lgd_code: '762' },
        { name: 'Sarangarh Bilaigarh', lgd_code: '763' },
        { name: 'Sukma', lgd_code: '642' },
        { name: 'Surajpur', lgd_code: '648' },
        { name: 'Surguja', lgd_code: '389' },
      ],
    },
    {
      name: 'Dadra and Nagar Haveli and Daman and Diu',
      lgd_code: '38',
      iso_code: 'IN-DH',
      districts: [
        { name: 'Dadra and Nagar Haveli', lgd_code: '465' },
        { name: 'Daman', lgd_code: '463' },
        { name: 'Diu', lgd_code: '464' },
      ],
    },
    {
      name: 'Delhi',
      lgd_code: '7',
      iso_code: 'IN-DL',
      districts: [
        { name: 'Central', lgd_code: '77' },
        { name: 'East', lgd_code: '78' },
        { name: 'New Delhi', lgd_code: '79' },
        { name: 'North', lgd_code: '80' },
        { name: 'North East', lgd_code: '81' },
        { name: 'North West', lgd_code: '82' },
        { name: 'Shahdara', lgd_code: '671' },
        { name: 'South', lgd_code: '83' },
        { name: 'South East', lgd_code: '670' },
        { name: 'South West', lgd_code: '84' },
        { name: 'West', lgd_code: '85' },
      ],
    },
    {
      name: 'Goa',
      lgd_code: '30',
      iso_code: 'IN-GA',
      districts: [
        { name: 'North Goa', lgd_code: '551' },
        { name: 'South Goa', lgd_code: '552' },
      ],
    },
    {
      name: 'Gujarat',
      lgd_code: '24',
      iso_code: 'IN-GJ',
      districts: [
        { name: 'Ahmadabad', lgd_code: '438' },
        { name: 'Amreli', lgd_code: '439' },
        { name: 'Anand', lgd_code: '440' },
        { name: 'Arvalli', lgd_code: '672' },
        { name: 'Banas Kantha', lgd_code: '441' },
        { name: 'Bharuch', lgd_code: '442' },
        { name: 'Bhavnagar', lgd_code: '443' },
        { name: 'Botad', lgd_code: '676' },
        { name: 'Chhotaudepur', lgd_code: '668' },
        { name: 'Dang', lgd_code: '444' },
        { name: 'Devbhumi Dwarka', lgd_code: '674' },
        { name: 'Dohad', lgd_code: '445' },
        { name: 'Gandhinagar', lgd_code: '446' },
        { name: 'Gir Somnath', lgd_code: '675' },
        { name: 'Jamnagar', lgd_code: '447' },
        { name: 'Junagadh', lgd_code: '448' },
        { name: 'Kachchh', lgd_code: '449' },
        { name: 'Kheda', lgd_code: '450' },
        { name: 'Mahesana', lgd_code: '451' },
        { name: 'Mahisagar', lgd_code: '669' },
        { name: 'Morbi', lgd_code: '673' },
        { name: 'Narmada', lgd_code: '452' },
        { name: 'Navsari', lgd_code: '453' },
        { name: 'Panch Mahals', lgd_code: '454' },
        { name: 'Patan', lgd_code: '455' },
        { name: 'Porbandar', lgd_code: '456' },
        { name: 'Rajkot', lgd_code: '457' },
        { name: 'Sabar Kantha', lgd_code: '458' },
        { name: 'Surat', lgd_code: '459' },
        { name: 'Surendranagar', lgd_code: '460' },
        { name: 'Tapi', lgd_code: '641' },
        { name: 'Vadodara', lgd_code: '461' },
        { name: 'Valsad', lgd_code: '462' },
      ],
    },
    {
      name: 'Haryana',
      lgd_code: '6',
      iso_code: 'IN-HR',
      districts: [
        { name: 'Ambala', lgd_code: '58' },
        { name: 'Bhiwani', lgd_code: '59' },
        { name: 'Charki Dadri', lgd_code: '701' },
        { name: 'Faridabad', lgd_code: '60' },
        { name: 'Fatehabad', lgd_code: '61' },
        { name: 'Gurugram', lgd_code: '62' },
        { name: 'Hisar', lgd_code: '63' },
        { name: 'Jhajjar', lgd_code: '64' },
        { name: 'Jind', lgd_code: '65' },
        { name: 'Kaithal', lgd_code: '66' },
        { name: 'Karnal', lgd_code: '67' },
        { name: 'Kurukshetra', lgd_code: '68' },
        { name: 'Mahendragarh', lgd_code: '69' },
        { name: 'Nuh', lgd_code: '604' },
        { name: 'Palwal', lgd_code: '619' },
        { name: 'Panchkula', lgd_code: '70' },
        { name: 'Panipat', lgd_code: '71' },
        { name: 'Rewari', lgd_code: '72' },
        { name: 'Rohtak', lgd_code: '73' },
        { name: 'Sirsa', lgd_code: '74' },
        { name: 'Sonipat', lgd_code: '75' },
        { name: 'Yamunanagar', lgd_code: '76' },
      ],
    },
    {
      name: 'Himachal Pradesh',
      lgd_code: '2',
      iso_code: 'IN-HP',
      districts: [
        { name: 'Bilaspur', lgd_code: '15' },
        { name: 'Chamba', lgd_code: '16' },
        { name: 'Hamirpur', lgd_code: '17' },
        { name: 'Kangra', lgd_code: '18' },
        { name: 'Kinnaur', lgd_code: '19' },
        { name: 'Kullu', lgd_code: '20' },
        { name: 'Lahul and Spiti', lgd_code: '21' },
        { name: 'Mandi', lgd_code: '22' },
        { name: 'Shimla', lgd_code: '23' },
        { name: 'Sirmaur', lgd_code: '24' },
        { name: 'Solan', lgd_code: '25' },
        { name: 'Una', lgd_code: '26' },
      ],
    },
    {
      name: 'Jammu and Kashmir',
      lgd_code: '1',
      iso_code: 'IN-JK',
      districts: [
        { name: 'Anantnag', lgd_code: '1' },
        { name: 'Bandipora', lgd_code: '623' },
        { name: 'Baramulla', lgd_code: '3' },
        { name: 'Budgam', lgd_code: '2' },
        { name: 'Doda', lgd_code: '4' },
        { name: 'Ganderbal', lgd_code: '626' },
        { name: 'Jammu', lgd_code: '5' },
        { name: 'Kathua', lgd_code: '7' },
        { name: 'Kishtwar', lgd_code: '620' },
        { name: 'Kulgam', lgd_code: '622' },
        { name: 'Kupwara', lgd_code: '8' },
        { name: 'Poonch', lgd_code: '10' },
        { name: 'Pulwama', lgd_code: '11' },
        { name: 'Rajouri', lgd_code: '12' },
        { name: 'Ramban', lgd_code: '621' },
        { name: 'Reasi', lgd_code: '627' },
        { name: 'Samba', lgd_code: '624' },
        { name: 'Shopian', lgd_code: '625' },
        { name: 'Srinagar', lgd_code: '13' },
        { name: 'Udhampur', lgd_code: '14' },
      ],
    },
    {
      name: 'Jharkhand',
      lgd_code: '20',
      iso_code: 'IN-JH',
      districts: [
        { name: 'Bokaro', lgd_code: '322' },
        { name: 'Chatra', lgd_code: '323' },
        { name: 'Deoghar', lgd_code: '324' },
        { name: 'Dhanbad', lgd_code: '325' },
        { name: 'Dumka', lgd_code: '326' },
        { name: 'East Singhbum', lgd_code: '327' },
        { name: 'Garhwa', lgd_code: '328' },
        { name: 'Giridih', lgd_code: '329' },
        { name: 'Godda', lgd_code: '330' },
        { name: 'Gumla', lgd_code: '331' },
        { name: 'Hazaribagh', lgd_code: '332' },
        { name: 'Jamtara', lgd_code: '333' },
        { name: 'Khunti', lgd_code: '606' },
        { name: 'Koderma', lgd_code: '334' },
        { name: 'Latehar', lgd_code: '335' },
        { name: 'Lohardaga', lgd_code: '336' },
        { name: 'Pakur', lgd_code: '337' },
        { name: 'Palamu', lgd_code: '338' },
        { name: 'Ramgarh', lgd_code: '607' },
        { name: 'Ranchi', lgd_code: '339' },
        { name: 'Sahebganj', lgd_code: '340' },
        { name: 'Saraikela Kharsawan', lgd_code: '341' },
        { name: 'Simdega', lgd_code: '342' },
        { name: 'West Singhbhum', lgd_code: '343' },
      ],
    },
    {
      name: 'Karnataka',
      lgd_code: '29',
      iso_code: 'IN-KA',
      districts: [
        { name: 'Bagalkote', lgd_code: '524' },
        { name: 'Ballari', lgd_code: '528' },
        { name: 'Belagavi', lgd_code: '527' },
        { name: 'Bengaluru Rural', lgd_code: '526' },
        { name: 'Bengaluru Urban', lgd_code: '525' },
        { name: 'Bidar', lgd_code: '529' },
        { name: 'Chamarajanagara', lgd_code: '531' },
        { name: 'Chikkaballapura', lgd_code: '630' },
        { name: 'Chikkamagaluru', lgd_code: '532' },
        { name: 'Chitradurga', lgd_code: '533' },
        { name: 'Dakshina Kannada', lgd_code: '534' },
        { name: 'Davangere', lgd_code: '535' },
        { name: 'Dharwad', lgd_code: '536' },
        { name: 'Gadag', lgd_code: '537' },
        { name: 'Hassan', lgd_code: '539' },
        { name: 'Haveri', lgd_code: '540' },
        { name: 'Kalaburagi', lgd_code: '538' },
        { name: 'Kodagu', lgd_code: '541' },
        { name: 'Kolar', lgd_code: '542' },
        { name: 'Koppal', lgd_code: '543' },
        { name: 'Mandya', lgd_code: '544' },
        { name: 'Mysuru', lgd_code: '545' },
        { name: 'Raichur', lgd_code: '546' },
        { name: 'Ramanagara', lgd_code: '631' },
        { name: 'Shivamogga', lgd_code: '547' },
        { name: 'Tumakuru', lgd_code: '548' },
        { name: 'Udupi', lgd_code: '549' },
        { name: 'Uttara Kannada', lgd_code: '550' },
        { name: 'Vijayanagar', lgd_code: '738' },
        { name: 'Vijayapura', lgd_code: '530' },
        { name: 'Yadgir', lgd_code: '635' },
      ],
    },
    {
      name: 'Kerala',
      lgd_code: '32',
      iso_code: 'IN-KL',
      districts: [
        { name: 'Alappuzha', lgd_code: '554' },
        { name: 'Ernakulam', lgd_code: '555' },
        { name: 'Idukki', lgd_code: '556' },
        { name: 'Kannur', lgd_code: '557' },
        { name: 'Kasaragod', lgd_code: '558' },
        { name: 'Kollam', lgd_code: '559' },
        { name: 'Kottayam', lgd_code: '560' },
        { name: 'Kozhikode', lgd_code: '561' },
        { name: 'Malappuram', lgd_code: '562' },
        { name: 'Palakkad', lgd_code: '563' },
        { name: 'Pathanamthitta', lgd_code: '564' },
        { name: 'Thiruvananthapuram', lgd_code: '565' },
        { name: 'Thrissur', lgd_code: '566' },
        { name: 'Wayanad', lgd_code: '567' },
      ],
    },
    {
      name: 'Ladakh',
      lgd_code: '37',
      iso_code: 'IN-LA',
      districts: [
        { name: 'Kargil', lgd_code: '6' },
        { name: 'Leh Ladakh', lgd_code: '9' },
      ],
    },
    {
      name: 'Lakshadweep',
      lgd_code: '31',
      iso_code: 'IN-LD',
      districts: [{ name: 'Lakshadweep District', lgd_code: '553' }],
    },
    {
      name: 'Madhya Pradesh',
      lgd_code: '23',
      iso_code: 'IN-MP',
      districts: [
        { name: 'Agar Malwa', lgd_code: '667' },
        { name: 'Alirajpur', lgd_code: '639' },
        { name: 'Anuppur', lgd_code: '390' },
        { name: 'Ashoknagar', lgd_code: '391' },
        { name: 'Balaghat', lgd_code: '392' },
        { name: 'Barwani', lgd_code: '393' },
        { name: 'Betul', lgd_code: '394' },
        { name: 'Bhind', lgd_code: '395' },
        { name: 'Bhopal', lgd_code: '396' },
        { name: 'Burhanpur', lgd_code: '397' },
        { name: 'Chhatarpur', lgd_code: '398' },
        { name: 'Chhindwara', lgd_code: '399' },
        { name: 'Damoh', lgd_code: '400' },
        { name: 'Datia', lgd_code: '401' },
        { name: 'Dewas', lgd_code: '402' },
        { name: 'Dhar', lgd_code: '403' },
        { name: 'Dindori', lgd_code: '404' },
        { name: 'East Nimar', lgd_code: '405' },
        { name: 'Guna', lgd_code: '406' },
        { name: 'Gwalior', lgd_code: '407' },
        { name: 'Harda', lgd_code: '408' },
        { name: 'Indore', lgd_code: '410' },
        { name: 'Jabalpur', lgd_code: '411' },
        { name: 'Jhabua', lgd_code: '412' },
        { name: 'Katni', lgd_code: '413' },
        { name: 'Khargone', lgd_code: '414' },
        { name: 'Mandla', lgd_code: '415' },
        { name: 'Mandsaur', lgd_code: '416' },
        { name: 'Morena', lgd_code: '417' },
        { name: 'Narmadapuram', lgd_code: '409' },
        { name: 'Narsinghpur', lgd_code: '418' },
        { name: 'Neemuch', lgd_code: '419' },
        { name: 'Niwari', lgd_code: '722' },
        { name: 'Panna', lgd_code: '420' },
        { name: 'Raisen', lgd_code: '421' },
        { name: 'Rajgarh', lgd_code: '422' },
        { name: 'Ratlam', lgd_code: '423' },
        { name: 'Rewa', lgd_code: '424' },
        { name: 'Sagar', lgd_code: '425' },
        { name: 'Satna', lgd_code: '426' },
        { name: 'Sehore', lgd_code: '427' },
        { name: 'Seoni', lgd_code: '428' },
        { name: 'Shahdol', lgd_code: '429' },
        { name: 'Shajapur', lgd_code: '430' },
        { name: 'Sheopur', lgd_code: '431' },
        { name: 'Shivpuri', lgd_code: '432' },
        { name: 'Sidhi', lgd_code: '433' },
        { name: 'Singrauli', lgd_code: '638' },
        { name: 'Tikamgarh', lgd_code: '434' },
        { name: 'Ujjain', lgd_code: '435' },
        { name: 'Umaria', lgd_code: '436' },
        { name: 'Vidisha', lgd_code: '437' },
      ],
    },
    {
      name: 'Maharashtra',
      lgd_code: '27',
      iso_code: 'IN-MH',
      districts: [
        { name: 'Ahmednagar', lgd_code: '466' },
        { name: 'Akola', lgd_code: '467' },
        { name: 'Amravati', lgd_code: '468' },
        { name: 'Aurangabad', lgd_code: '469' },
        { name: 'Beed', lgd_code: '470' },
        { name: 'Bhandara', lgd_code: '471' },
        { name: 'Buldhana', lgd_code: '472' },
        { name: 'Chandrapur', lgd_code: '473' },
        { name: 'Dhule', lgd_code: '474' },
        { name: 'Gadchiroli', lgd_code: '475' },
        { name: 'Gondia', lgd_code: '476' },
        { name: 'Hingoli', lgd_code: '477' },
        { name: 'Jalgaon', lgd_code: '478' },
        { name: 'Jalna', lgd_code: '479' },
        { name: 'Kolhapur', lgd_code: '480' },
        { name: 'Latur', lgd_code: '481' },
        { name: 'Mumbai', lgd_code: '482' },
        { name: 'Mumbai Suburban', lgd_code: '483' },
        { name: 'Nagpur', lgd_code: '484' },
        { name: 'Nanded', lgd_code: '485' },
        { name: 'Nandurbar', lgd_code: '486' },
        { name: 'Nashik', lgd_code: '487' },
        { name: 'Osmanabad', lgd_code: '488' },
        { name: 'Palghar', lgd_code: '665' },
        { name: 'Parbhani', lgd_code: '489' },
        { name: 'Pune', lgd_code: '490' },
        { name: 'Raigad', lgd_code: '491' },
        { name: 'Ratnagiri', lgd_code: '492' },
        { name: 'Sangli', lgd_code: '493' },
        { name: 'Satara', lgd_code: '494' },
        { name: 'Sindhudurg', lgd_code: '495' },
        { name: 'Solapur', lgd_code: '496' },
        { name: 'Thane', lgd_code: '497' },
        { name: 'Wardha', lgd_code: '498' },
        { name: 'Washim', lgd_code: '499' },
        { name: 'Yavatmal', lgd_code: '500' },
      ],
    },
    {
      name: 'Manipur',
      lgd_code: '14',
      iso_code: 'IN-MN',
      districts: [
        { name: 'Bishnupur', lgd_code: '252' },
        { name: 'Chandel', lgd_code: '253' },
        { name: 'Churachandpur', lgd_code: '254' },
        { name: 'Imphal East', lgd_code: '255' },
        { name: 'Imphal West', lgd_code: '256' },
        { name: 'Jiribam', lgd_code: '713' },
        { name: 'Kakching', lgd_code: '711' },
        { name: 'Kamjong', lgd_code: '717' },
        { name: 'Kangpokpi', lgd_code: '712' },
        { name: 'Noney', lgd_code: '714' },
        { name: 'Pherzawl', lgd_code: '715' },
        { name: 'Senapati', lgd_code: '257' },
        { name: 'Tamenglong', lgd_code: '258' },
        { name: 'Tengnoupal', lgd_code: '716' },
        { name: 'Thoubal', lgd_code: '259' },
        { name: 'Ukhrul', lgd_code: '260' },
      ],
    },
    {
      name: 'Meghalaya',
      lgd_code: '17',
      iso_code: 'IN-ML',
      districts: [
        { name: 'East Garo Hills', lgd_code: '273' },
        { name: 'East Jaintia Hills', lgd_code: '657' },
        { name: 'East Khasi Hills', lgd_code: '274' },
        { name: 'Eastern West Khasi Hills', lgd_code: '740' },
        { name: 'North Garo Hills', lgd_code: '656' },
        { name: 'Ri Bhoi', lgd_code: '276' },
        { name: 'South Garo Hills', lgd_code: '277' },
        { name: 'South West Garo Hills', lgd_code: '663' },
        { name: 'South West Khasi Hills', lgd_code: '658' },
        { name: 'West Garo Hills', lgd_code: '278' },
        { name: 'West Jaintia Hills', lgd_code: '275' },
        { name: 'West Khasi Hills', lgd_code: '279' },
      ],
    },
    {
      name: 'Mizoram',
      lgd_code: '15',
      iso_code: 'IN-MZ',
      districts: [
        { name: 'Aizawl', lgd_code: '261' },
        { name: 'Champhai', lgd_code: '262' },
        { name: 'Hnahthial', lgd_code: '726' },
        { name: 'Khawzawl', lgd_code: '728' },
        { name: 'Kolasib', lgd_code: '263' },
        { name: 'Lawngtlai', lgd_code: '264' },
        { name: 'Lunglei', lgd_code: '265' },
        { name: 'Mamit', lgd_code: '266' },
        { name: 'Saiha', lgd_code: '267' },
        { name: 'Saitual', lgd_code: '727' },
        { name: 'Serchhip', lgd_code: '268' },
      ],
    },
    {
      name: 'Nagaland',
      lgd_code: '13',
      iso_code: 'IN-NL',
      districts: [
        { name: 'Chumoukedima', lgd_code: '758' },
        { name: 'Dimapur', lgd_code: '244' },
        { name: 'Kiphire', lgd_code: '614' },
        { name: 'Kohima', lgd_code: '245' },
        { name: 'Longleng', lgd_code: '615' },
        { name: 'Mokokchung', lgd_code: '246' },
        { name: 'Mon', lgd_code: '247' },
        { name: 'Niuland', lgd_code: '764' },
        { name: 'Noklak', lgd_code: '736' },
        { name: 'Peren', lgd_code: '613' },
        { name: 'Phek', lgd_code: '248' },
        { name: 'Shamator', lgd_code: '765' },
        { name: 'Tseminyu', lgd_code: '757' },
        { name: 'Tuensang', lgd_code: '249' },
        { name: 'Wokha', lgd_code: '250' },
        { name: 'Zunheboto', lgd_code: '251' },
      ],
    },
    {
      name: 'Odisha',
      lgd_code: '21',
      iso_code: 'IN-OD',
      districts: [
        { name: 'Anugul', lgd_code: '344' },
        { name: 'Balangir', lgd_code: '345' },
        { name: 'Baleshwar', lgd_code: '346' },
        { name: 'Bargarh', lgd_code: '347' },
        { name: 'Bhadrak', lgd_code: '348' },
        { name: 'Boudh', lgd_code: '349' },
        { name: 'Cuttack', lgd_code: '350' },
        { name: 'Deogarh', lgd_code: '351' },
        { name: 'Dhenkanal', lgd_code: '352' },
        { name: 'Gajapati', lgd_code: '353' },
        { name: 'Ganjam', lgd_code: '354' },
        { name: 'Jagatsinghapur', lgd_code: '355' },
        { name: 'Jajapur', lgd_code: '356' },
        { name: 'Jharsuguda', lgd_code: '357' },
        { name: 'Kalahandi', lgd_code: '358' },
        { name: 'Kandhamal', lgd_code: '359' },
        { name: 'Kendrapara', lgd_code: '360' },
        { name: 'Kendujhar', lgd_code: '361' },
        { name: 'Khordha', lgd_code: '362' },
        { name: 'Koraput', lgd_code: '363' },
        { name: 'Malkangiri', lgd_code: '364' },
        { name: 'Mayurbhanj', lgd_code: '365' },
        { name: 'Nabarangpur', lgd_code: '366' },
        { name: 'Nayagarh', lgd_code: '367' },
        { name: 'Nuapada', lgd_code: '368' },
        { name: 'Puri', lgd_code: '369' },
        { name: 'Rayagada', lgd_code: '370' },
        { name: 'Sambalpur', lgd_code: '371' },
        { name: 'Sonepur', lgd_code: '372' },
        { name: 'Sundargarh', lgd_code: '373' },
      ],
    },
    {
      name: 'Puducherry',
      lgd_code: '34',
      iso_code: 'IN-PY',
      districts: [
        { name: 'Karaikal', lgd_code: '598' },
        { name: 'Mahe', lgd_code: '599' },
        { name: 'Pondicherry', lgd_code: '600' },
        { name: 'Yanam', lgd_code: '601' },
      ],
    },
    {
      name: 'Punjab',
      lgd_code: '3',
      iso_code: 'IN-PB',
      districts: [
        { name: 'Amritsar', lgd_code: '27' },
        { name: 'Barnala', lgd_code: '605' },
        { name: 'Bathinda', lgd_code: '28' },
        { name: 'Faridkot', lgd_code: '29' },
        { name: 'Fatehgarh Sahib', lgd_code: '30' },
        { name: 'Fazilka', lgd_code: '651' },
        { name: 'Ferozepur', lgd_code: '31' },
        { name: 'Gurdaspur', lgd_code: '32' },
        { name: 'Hoshiarpur', lgd_code: '33' },
        { name: 'Jalandhar', lgd_code: '34' },
        { name: 'Kapurthala', lgd_code: '35' },
        { name: 'Ludhiana', lgd_code: '36' },
        { name: 'Malerkotla', lgd_code: '737' },
        { name: 'Mansa', lgd_code: '37' },
        { name: 'Moga', lgd_code: '38' },
        { name: 'Pathankot', lgd_code: '662' },
        { name: 'Patiala', lgd_code: '41' },
        { name: 'Rupnagar', lgd_code: '42' },
        { name: 'S.a.s Nagar', lgd_code: '608' },
        { name: 'Sangrur', lgd_code: '43' },
        { name: 'Shahid Bhagat Singh Nagar', lgd_code: '40' },
        { name: 'Sri Muktsar Sahib', lgd_code: '39' },
        { name: 'Tarn Taran', lgd_code: '609' },
      ],
    },
    {
      name: 'Rajasthan',
      lgd_code: '8',
      iso_code: 'IN-RJ',
      districts: [
        { name: 'Ajmer', lgd_code: '86' },
        { name: 'Alwar', lgd_code: '87' },
        { name: 'Banswara', lgd_code: '88' },
        { name: 'Baran', lgd_code: '89' },
        { name: 'Barmer', lgd_code: '90' },
        { name: 'Bharatpur', lgd_code: '91' },
        { name: 'Bhilwara', lgd_code: '92' },
        { name: 'Bikaner', lgd_code: '93' },
        { name: 'Bundi', lgd_code: '94' },
        { name: 'Chittorgarh', lgd_code: '95' },
        { name: 'Churu', lgd_code: '96' },
        { name: 'Dausa', lgd_code: '97' },
        { name: 'Dholpur', lgd_code: '98' },
        { name: 'Dungarpur', lgd_code: '99' },
        { name: 'Ganganagar', lgd_code: '100' },
        { name: 'Hanumangarh', lgd_code: '101' },
        { name: 'Jaipur', lgd_code: '102' },
        { name: 'Jaisalmer', lgd_code: '103' },
        { name: 'Jalore', lgd_code: '104' },
        { name: 'Jhalawar', lgd_code: '105' },
        { name: 'Jhunjhunu', lgd_code: '106' },
        { name: 'Jodhpur', lgd_code: '107' },
        { name: 'Karauli', lgd_code: '108' },
        { name: 'Kota', lgd_code: '109' },
        { name: 'Nagaur', lgd_code: '110' },
        { name: 'Pali', lgd_code: '111' },
        { name: 'Pratapgarh', lgd_code: '629' },
        { name: 'Rajsamand', lgd_code: '112' },
        { name: 'Sawai Madhopur', lgd_code: '113' },
        { name: 'Sikar', lgd_code: '114' },
        { name: 'Sirohi', lgd_code: '115' },
        { name: 'Tonk', lgd_code: '116' },
        { name: 'Udaipur', lgd_code: '117' },
      ],
    },
    {
      name: 'Sikkim',
      lgd_code: '11',
      iso_code: 'IN-SK',
      districts: [
        { name: 'Gangtok', lgd_code: '225' },
        { name: 'Gyalshing', lgd_code: '228' },
        { name: 'Mangan', lgd_code: '226' },
        { name: 'Namchi', lgd_code: '227' },
        { name: 'Pakyong', lgd_code: '741' },
        { name: 'Soreng', lgd_code: '742' },
      ],
    },
    {
      name: 'Tamil Nadu',
      lgd_code: '33',
      iso_code: 'IN-TN',
      districts: [
        { name: 'Ariyalur', lgd_code: '610' },
        { name: 'Chengalpattu', lgd_code: '730' },
        { name: 'Chennai', lgd_code: '568' },
        { name: 'Coimbatore', lgd_code: '569' },
        { name: 'Cuddalore', lgd_code: '570' },
        { name: 'Dharmapuri', lgd_code: '571' },
        { name: 'Dindigul', lgd_code: '572' },
        { name: 'Erode', lgd_code: '573' },
        { name: 'Kallakurichi', lgd_code: '729' },
        { name: 'Kanchipuram', lgd_code: '574' },
        { name: 'Kanniyakumari', lgd_code: '575' },
        { name: 'Karur', lgd_code: '576' },
        { name: 'Krishnagiri', lgd_code: '577' },
        { name: 'Madurai', lgd_code: '578' },
        { name: 'Mayiladuthurai', lgd_code: '735' },
        { name: 'Nagapattinam', lgd_code: '579' },
        { name: 'Namakkal', lgd_code: '580' },
        { name: 'Perambalur', lgd_code: '581' },
        { name: 'Pudukkottai', lgd_code: '582' },
        { name: 'Ramanathapuram', lgd_code: '583' },
        { name: 'Ranipet', lgd_code: '731' },
        { name: 'Salem', lgd_code: '584' },
        { name: 'Sivaganga', lgd_code: '585' },
        { name: 'Tenkasi', lgd_code: '733' },
        { name: 'Thanjavur', lgd_code: '586' },
        { name: 'The Nilgiris', lgd_code: '587' },
        { name: 'Theni', lgd_code: '588' },
        { name: 'Thiruvallur', lgd_code: '589' },
        { name: 'Thiruvarur', lgd_code: '590' },
        { name: 'Tiruchirappalli', lgd_code: '591' },
        { name: 'Tirunelveli', lgd_code: '592' },
        { name: 'Tirupathur', lgd_code: '732' },
        { name: 'Tiruppur', lgd_code: '634' },
        { name: 'Tiruvannamalai', lgd_code: '593' },
        { name: 'Tuticorin', lgd_code: '594' },
        { name: 'Vellore', lgd_code: '595' },
        { name: 'Villupuram', lgd_code: '596' },
        { name: 'Virudhunagar', lgd_code: '597' },
      ],
    },
    {
      name: 'Telangana',
      lgd_code: '36',
      iso_code: 'IN-TS',
      districts: [
        { name: 'Adilabad', lgd_code: '501' },
        { name: 'Bhadradri Kothagudem', lgd_code: '690' },
        { name: 'Hanumakonda', lgd_code: '686' },
        { name: 'Hyderabad', lgd_code: '507' },
        { name: 'Jagitial', lgd_code: '681' },
        { name: 'Jangoan', lgd_code: '689' },
        { name: 'Jayashankar Bhupalapally', lgd_code: '687' },
        { name: 'Jogulamba Gadwal', lgd_code: '695' },
        { name: 'Kamareddy', lgd_code: '685' },
        { name: 'Karimnagar', lgd_code: '508' },
        { name: 'Khammam', lgd_code: '509' },
        { name: 'Kumuram Bheem Asifabad', lgd_code: '699' },
        { name: 'Mahabubabad', lgd_code: '688' },
        { name: 'Mahabubnagar', lgd_code: '512' },
        { name: 'Mancherial', lgd_code: '684' },
        { name: 'Medak', lgd_code: '513' },
        { name: 'Medchal Malkajgiri', lgd_code: '700' },
        { name: 'Mulugu', lgd_code: '720' },
        { name: 'Nagarkurnool', lgd_code: '694' },
        { name: 'Nalgonda', lgd_code: '514' },
        { name: 'Narayanpet', lgd_code: '721' },
        { name: 'Nirmal', lgd_code: '680' },
        { name: 'Nizamabad', lgd_code: '516' },
        { name: 'Peddapalli', lgd_code: '682' },
        { name: 'Rajanna Sircilla', lgd_code: '683' },
        { name: 'Ranga Reddy', lgd_code: '518' },
        { name: 'Sangareddy', lgd_code: '691' },
        { name: 'Siddipet', lgd_code: '692' },
        { name: 'Suryapet', lgd_code: '696' },
        { name: 'Vikarabad', lgd_code: '698' },
        { name: 'Wanaparthy', lgd_code: '693' },
        { name: 'Warangal', lgd_code: '522' },
        { name: 'Yadadri Bhuvanagiri', lgd_code: '697' },
      ],
    },
    {
      name: 'Tripura',
      lgd_code: '16',
      iso_code: 'IN-TR',
      districts: [
        { name: 'Dhalai', lgd_code: '269' },
        { name: 'Gomati', lgd_code: '654' },
        { name: 'Khowai', lgd_code: '652' },
        { name: 'North Tripura', lgd_code: '270' },
        { name: 'Sepahijala', lgd_code: '653' },
        { name: 'South Tripura', lgd_code: '271' },
        { name: 'Unakoti', lgd_code: '655' },
        { name: 'West Tripura', lgd_code: '272' },
      ],
    },
    {
      name: 'Uttar Pradesh',
      lgd_code: '9',
      iso_code: 'IN-UP',
      districts: [
        { name: 'Agra', lgd_code: '118' },
        { name: 'Aligarh', lgd_code: '119' },
        { name: 'Ambedkar Nagar', lgd_code: '121' },
        { name: 'Amethi', lgd_code: '640' },
        { name: 'Amroha', lgd_code: '154' },
        { name: 'Auraiya', lgd_code: '122' },
        { name: 'Ayodhya', lgd_code: '140' },
        { name: 'Azamgarh', lgd_code: '123' },
        { name: 'Baghpat', lgd_code: '124' },
        { name: 'Bahraich', lgd_code: '125' },
        { name: 'Ballia', lgd_code: '126' },
        { name: 'Balrampur', lgd_code: '127' },
        { name: 'Banda', lgd_code: '128' },
        { name: 'Barabanki', lgd_code: '129' },
        { name: 'Bareilly', lgd_code: '130' },
        { name: 'Basti', lgd_code: '131' },
        { name: 'Bhadohi', lgd_code: '179' },
        { name: 'Bijnor', lgd_code: '132' },
        { name: 'Budaun', lgd_code: '133' },
        { name: 'Bulandshahr', lgd_code: '134' },
        { name: 'Chandauli', lgd_code: '135' },
        { name: 'Chitrakoot', lgd_code: '136' },
        { name: 'Deoria', lgd_code: '137' },
        { name: 'Etah', lgd_code: '138' },
        { name: 'Etawah', lgd_code: '139' },
        { name: 'Farrukhabad', lgd_code: '141' },
        { name: 'Fatehpur', lgd_code: '142' },
        { name: 'Firozabad', lgd_code: '143' },
        { name: 'Gautam Buddha Nagar', lgd_code: '144' },
        { name: 'Ghaziabad', lgd_code: '145' },
        { name: 'Ghazipur', lgd_code: '146' },
        { name: 'Gonda', lgd_code: '147' },
        { name: 'Gorakhpur', lgd_code: '148' },
        { name: 'Hamirpur', lgd_code: '149' },
        { name: 'Hapur', lgd_code: '661' },
        { name: 'Hardoi', lgd_code: '150' },
        { name: 'Hathras', lgd_code: '163' },
        { name: 'Jalaun', lgd_code: '151' },
        { name: 'Jaunpur', lgd_code: '152' },
        { name: 'Jhansi', lgd_code: '153' },
        { name: 'Kannauj', lgd_code: '155' },
        { name: 'Kanpur Dehat', lgd_code: '156' },
        { name: 'Kanpur Nagar', lgd_code: '157' },
        { name: 'Kasganj', lgd_code: '633' },
        { name: 'Kaushambi', lgd_code: '158' },
        { name: 'Kheri', lgd_code: '159' },
        { name: 'Kushi Nagar', lgd_code: '160' },
        { name: 'Lalitpur', lgd_code: '161' },
        { name: 'Lucknow', lgd_code: '162' },
        { name: 'Maharajganj', lgd_code: '164' },
        { name: 'Mahoba', lgd_code: '165' },
        { name: 'Mainpuri', lgd_code: '166' },
        { name: 'Mathura', lgd_code: '167' },
        { name: 'Mau', lgd_code: '168' },
        { name: 'Meerut', lgd_code: '169' },
        { name: 'Mirzapur', lgd_code: '170' },
        { name: 'Moradabad', lgd_code: '171' },
        { name: 'Muzaffarnagar', lgd_code: '172' },
        { name: 'Pilibhit', lgd_code: '173' },
        { name: 'Pratapgarh', lgd_code: '174' },
        { name: 'Prayagraj', lgd_code: '120' },
        { name: 'Rae Bareli', lgd_code: '175' },
        { name: 'Rampur', lgd_code: '176' },
        { name: 'Saharanpur', lgd_code: '177' },
        { name: 'Sambhal', lgd_code: '659' },
        { name: 'Sant Kabeer Nagar', lgd_code: '178' },
        { name: 'Shahjahanpur', lgd_code: '180' },
        { name: 'Shamli', lgd_code: '660' },
        { name: 'Shravasti', lgd_code: '181' },
        { name: 'Siddharth Nagar', lgd_code: '182' },
        { name: 'Sitapur', lgd_code: '183' },
        { name: 'Sonbhadra', lgd_code: '184' },
        { name: 'Sultanpur', lgd_code: '185' },
        { name: 'Unnao', lgd_code: '186' },
        { name: 'Varanasi', lgd_code: '187' },
      ],
    },
    {
      name: 'Uttarakhand',
      lgd_code: '5',
      iso_code: 'IN-UK',
      districts: [
        { name: 'Almora', lgd_code: '45' },
        { name: 'Bageshwar', lgd_code: '46' },
        { name: 'Chamoli', lgd_code: '47' },
        { name: 'Champawat', lgd_code: '48' },
        { name: 'Dehradun', lgd_code: '49' },
        { name: 'Haridwar', lgd_code: '50' },
        { name: 'Nainital', lgd_code: '51' },
        { name: 'Pauri Garhwal', lgd_code: '52' },
        { name: 'Pithoragarh', lgd_code: '53' },
        { name: 'Rudra Prayag', lgd_code: '54' },
        { name: 'Tehri Garhwal', lgd_code: '55' },
        { name: 'Udam Singh Nagar', lgd_code: '56' },
        { name: 'Uttar Kashi', lgd_code: '57' },
      ],
    },
    {
      name: 'West Bengal',
      lgd_code: '19',
      iso_code: 'IN-WB',
      districts: [
        { name: '24 Paraganas North', lgd_code: '303' },
        { name: '24 Paraganas South', lgd_code: '304' },
        { name: 'Alipurduar', lgd_code: '664' },
        { name: 'Bankura', lgd_code: '305' },
        { name: 'Birbhum', lgd_code: '307' },
        { name: 'Coochbehar', lgd_code: '308' },
        { name: 'Darjeeling', lgd_code: '309' },
        { name: 'Dinajpur Dakshin', lgd_code: '310' },
        { name: 'Dinajpur Uttar', lgd_code: '311' },
        { name: 'Hooghly', lgd_code: '312' },
        { name: 'Howrah', lgd_code: '313' },
        { name: 'Jalpaiguri', lgd_code: '314' },
        { name: 'Jhargram', lgd_code: '703' },
        { name: 'Kalimpong', lgd_code: '702' },
        { name: 'Kolkata', lgd_code: '315' },
        { name: 'Maldah', lgd_code: '316' },
        { name: 'Medinipur East', lgd_code: '317' },
        { name: 'Medinipur West', lgd_code: '318' },
        { name: 'Murshidabad', lgd_code: '319' },
        { name: 'Nadia', lgd_code: '320' },
        { name: 'Paschim Bardhaman', lgd_code: '704' },
        { name: 'Purba Bardhaman', lgd_code: '306' },
        { name: 'Purulia', lgd_code: '321' },
      ],
    },
  ],
};
