import { Controller, Get, NotFoundException, Param, Res } from '@nestjs/common';
import { ApiOkResponse, ApiParam, ApiTags } from '@nestjs/swagger';
import type { Response } from 'express';
import { join } from 'path';

/**
 * Public brand assets served by the API itself, so outgoing email can embed the
 * Nucleus logo and Swagger can show the favicon without a separate static host.
 *
 * The files are GENERATED by scripts/brand (never hand-edited) into
 * src/brand/assets and copied to dist/brand/assets by the nest-cli `assets`
 * rule — hence `__dirname`, which points at the right folder both under
 * `nest start --watch` and inside the Docker image (which ships only dist/).
 */
const ASSETS_DIR = join(__dirname, 'assets');

/** Explicit allow-list — nothing else in the folder is reachable. */
const PUBLIC_FILES = new Set([
  'email-logo.png',
  'favicon.svg',
  'mark-192.png',
  'mark-512.png',
  'nucleus-logo-horizontal.svg',
]);

@ApiTags('brand')
@Controller('brand')
export class BrandController {
  @Get(':file')
  @ApiParam({ name: 'file', enum: [...PUBLIC_FILES] })
  @ApiOkResponse({ description: 'The asset (PNG or SVG).' })
  serve(@Param('file') file: string, @Res() res: Response): void {
    if (!PUBLIC_FILES.has(file)) throw new NotFoundException();
    // Express sets Content-Type / ETag / Last-Modified, answers HEAD and 304,
    // and refuses anything outside `root`. Assets change only with a deploy;
    // a week keeps mail-client image proxies from re-fetching on every open.
    res.sendFile(file, { root: ASSETS_DIR, maxAge: '7d' }, (err) => {
      if (err && !res.headersSent) res.status(404).end();
    });
  }
}
